/*
 * CorpSite API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace CorpSiteAPI.Controllers.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EmployeePage : IEquatable<EmployeePage>
    { 
        /// <summary>
        /// List of employees.
        /// </summary>
        [Required]
        [DataMember(Name="employees")]
        public IList<Employee> Employees { get; set; }

        /// <summary>
        /// The total number of results from the query.
        /// </summary>
        [Required]
        [DataMember(Name="total")]
        public int? Total { get; set; }

        /// <summary>
        /// The offset of the first item in employees from the beginning of the results.
        /// </summary>
        [Required]
        [DataMember(Name = "offset")]
        public int? Offset { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmployeePage {\n");
            sb.Append("  Employees: ").Append(Employees).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmployeePage)obj);
        }

        /// <summary>
        /// Returns true if EmployeePage instances are equal
        /// </summary>
        /// <param name="other">Instance of EmployeePage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmployeePage other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Employees == other.Employees ||
                    Employees != null &&
                    Employees.SequenceEqual(other.Employees)
                ) && 
                (
                    Total == other.Total ||
                    Total != null &&
                    Total.Equals(other.Total)
                ) && 
                (
                    Offset == other.Offset ||
                    Offset != null &&
                    Offset.Equals(other.Offset)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Employees != null)
                    hashCode = hashCode * 59 + Employees.GetHashCode();
                    if (Total != null)
                    hashCode = hashCode * 59 + Total.GetHashCode();
                    if (Offset != null)
                    hashCode = hashCode * 59 + Offset.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmployeePage left, EmployeePage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmployeePage left, EmployeePage right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
